### ISSUE TITLE
Order of RTI Data Sync API uploads

### ISSUE THREAD

**Issue by will-at-rti** [AR-k12code/RTI_Scheduler#1]
First off, thanks for publishing this repository! What an awesome way to share the Cognos integration script with other schools.

One minor issue I noticed while glossing over the script was the order in which the uploads are done. If you are running this script for the first time on a school, the ordering is important because the different objects are created on separate transactions. 

Minor issue, because it only causes incomplete data the first 1 or 2 times you run it.

Example:
You can specify Instructor IDs within the Student Sync to set an advisory/homeroom instructor on each student record. But if your Instructor sync has never previously run, the Student Sync will result in warnings because the Instructor would not be found. The sync will still run, but the advisors would be missing.

It looks like Line 53 of RTIScheduler.ps1 can just its order changed to this to fix the issue. I don't have any sort of access to Cognos to test the entirety of this script.
`  @('Courses','Instructors','Students','Schedule','Performance') | ForEach-Object {`

**Comment by carbm1** [comment]
Good to know! I have updated the code for this.
